# Working with NumPY

In [10]:
import numpy as np

In [11]:
arr = np.array([1, 3, 4, 5, 6])
arr

array([1, 3, 4, 5, 6])

In [12]:
print(arr)

[1 3 4 5 6]


In [28]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [16]:
arr_3d = np.array([[[1, 2], [4, 5]], [[4, 5], [5, 6]]])
print(arr_3d)

[[[1 2]
  [4 5]]

 [[4 5]
  [5 6]]]


In [17]:
arr_2d.shape

(2, 3)

In [18]:
arr_2d.size

6

In [19]:
arr_3d.shape

(2, 2, 2)

In [20]:
arr_3d.dtype

dtype('int64')

In [21]:
# slicing and Indexing

new_arr = arr[1:4]     #slicing
print(new_arr)

ele = arr_2d[1][1]      # indexing
print(ele)

[3 4 5]
5


# Array Operations

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6]) 

arr_sum = arr1 + arr2
print(arr_sum)

[5 7 9]


In [23]:
arr_mul = arr1 * arr2
print(arr_mul)

[ 4 10 18]


In [24]:
print(arr1 * 5)

[ 5 10 15]


In [25]:
# shape same hunu pareyo otherwise no 
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6]) 

arr_sum = arr1 + arr2
print(arr_sum)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [26]:
mat1 =np.matrix([[1, 2], [3, 4]])
mat2 =np.matrix([[2, 3], [4, 5]])


In [27]:
print(f"First Matrix:\n{mat1}")
print(f"First Matrix:\n{mat2}")

First Matrix:
[[1 2]
 [3 4]]
First Matrix:
[[2 3]
 [4 5]]


In [43]:
mat_add = mat1 +mat2   # Addition
print(mat_add)

[[3 5]
 [7 9]]


In [44]:
# subtraction

mat_sub = mat1 - mat2
print(mat_sub)

[[-1 -1]
 [-1 -1]]


In [45]:
print(mat1 * 3)

[[ 3  6]
 [ 9 12]]


In [46]:
mat_mul = mat1 * mat2
print(mat_mul)

[[10 13]
 [22 29]]


mat_mul = mat1 @ mat2    
print(mat_mul)

print(np.dot(mat1, mat2))


In [47]:
# Transpose

print(mat_mul.T)

[[10 22]
 [13 29]]


In [52]:
# Matrix Inverse
print(np.linalg.inv(mat_mul))
      

[[ 7.25 -3.25]
 [-5.5   2.5 ]]


In [51]:
print(np.linalg.det(mat1))

-2.0000000000000004


In [53]:
print(np.linalg.eig(mat1))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))


## Vector Calculation

In [59]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 4, 5])
print("v1 =", v1)
print("v2 =", v2)

v1 = [1 2 3]
v2 = [3 4 5]


In [60]:
dot_product = np.dot(v1, v2)     # same
print(dot_product)

26


In [61]:
v1 @ v2     # dot product

np.int64(26)

In [62]:
print(v1 @ v2)        # same

26


In [63]:
cross_product = np.cross(v1, v2)     # cross product
print(cross_product)  

[-2  4 -2]


```
i j k
1 2 3
3 4 5

i (10-12) -j(5-9) + k(4-6)
-2i+4j-2k
(-2 4 -2)
```

# solve linear equation
2x + y = 5
x + y = 3
----------
x = 2

y = 1

In [72]:
A * X = B
X = (A inv) B


SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1152463098.py, line 1)

In [73]:
A = np.array([[2, 1], [1, 1]])
B = np. array([5, 3])

X = np.linalg.solve(A, B)
print("Value of (X,y):", X)

Value of (X,y): [2. 1.]


In [71]:
np.random.randn(3, 3)

array([[-0.13610898, -0.01606297,  0.64714423],
       [ 1.0338608 ,  0.37264801,  0.87698018],
       [-0.14792102, -0.33187361, -0.62522428]])